[files]
extend-exclude = [
  "data/fonts/**",
  "data/icons/**",
  "data/licenses/**",
  "Cargo.lock",
]

[default.extend-words]
Omarchy = "Omarchy"
Hyprland = "Hyprland"
JetBrains = "JetBrains"
Darcula = "Darcula"
darcula = "darcula"
Strata = "Strata"
WRONLY = "WRONLY"
gir = "gir"
